version: '3'

services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
